### ISSUE TITLE
Ability to view data for all regions

### ISSUE THREAD

**Issue by RichardoC** [Marchusness/cloud_ping#1]
Thanks for making this tool, I was wondering how I can access the latency data from all cloudflare regions? Are there API parameters I can use for that? 

Currently if I access <https://api.cloudping.dev/> I only get the details for the closest cloudflare region to my location

I'd like to see which region is likely to be best for me to use based on the latency for my users expected geography.

Thanks again

**Comment by Marchusness** [comment]
i updated the api to accept a cloudflare DC eg. https://api.cloudping.dev/?cloudflareDataCenterAirportCode=SYD

then claude this website showing the latency matrix https://marchusness.github.io/cloud_ping/web/

Hope that helps :)
